apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecodash-api
  labels:
    app: ecodash-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecodash-api
  template:
    metadata:
      labels:
        app: ecodash-api
    spec:
      containers:
        - name: ecodash-api
          image: docker.io/maldnuscarlsen/ecodash-api:506f31c7790f683a9698ebfc38aad4e4dc2127f4
          ports:
            - containerPort: 8080