apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecodash-web
  labels:
    app: ecodash-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecodash-web
  template:
    metadata:
      labels:
        app: ecodash-web
    spec:
      containers:
        - name: ecodash-web
          image: docker.io/maldnuscarlsen/ecodash-web:7052b0bcf95e2d2de738efe3ac0393d809825fad
          ports:
            - containerPort: 80